### ISSUE TITLE
Error WHMCS 7.8

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#51]
Hello!

When updating the WHMCS version to the new 7.8 it won't let me access anything, I get this error:

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

Whoops\Exception\ErrorException: require(): Failed opening required '****/modules/addons/openprovider/vendor/composer/../wedevelopcoffee/wpower/src/helpers.php' (include_path='.') in /*****/modules/addons/openprovider/vendor/composer/autoload_real.php:66
Stack trace:
#0 /*****/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require(): Fail...', '/****/...', 66)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by lucasRolff** [comment]
We have this issue as well. It can be resolved temporarily by going to `/modules/addons/openprovider/vendor/composer/../wedevelopcoffee/` then `cp -pr wPower wpower`

**Comment by soberoctober** [comment]
Yes, this is a known bug. 

Within the repository, there are both `modules/addons/openprovider/vendor/wedevelopcoffee`  wpower and wPower directories. wPower will be removed in v3.0.

As a temporary w/a rename wPower to wpower in `modules/addons/openprovider/vendor/wedevelopcoffee`.

**Comment by soberoctober** [comment]
fixed in [v3.0](https://github.com/openprovider/OP-WHMCS7/tree/v3.0)

**Comment by hostingwalk** [comment]
Error: Call to undefined function wLaunch() in /modules/addons/openprovider/openprovider.php:74
Stack trace:
#0 /public_html/admin/addonmodules.php(0): openprovider_output(Array)
#1 {main}

I still have this issue.
